# Generated by Django 4.1.11 on 2023-09-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
